package com.saber.pojo;

import lombok.Data;
import tk.mybatis.mapper.annotation.KeySql;

import javax.persistence.Id;
import javax.persistence.Table;

@Data
@Table(name = "people")
public class People {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.Id
     *
     * @mbg.generated
     */
    @Id
    @KeySql(useGeneratedKeys = true)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.age
     *
     * @mbg.generated
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.address
     *
     * @mbg.generated
     */
    private String address;



}